# Generated by Django 6.0.7 on 2026-07-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('staff', 'Nhân viên'), ('customer', 'Khách hàng')], default='customer', max_length=20),
        ),
    ]
